DROP DATABASE CLASIFICADOSAPP;
CREATE DATABASE CLASIFICADOSAPP;
USE CLASIFICADOSAPP;

CREATE TABLE USUARIOS (
	ID  INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL,
    APELLIDO VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    PASSWD VARCHAR(8) NOT NULL
)  ENGINE=INNODB CHARACTER SET utf8 COLLATE utf8_general_ci;

INSERT INTO USUARIOS (NOMBRE, APELLIDO, EMAIL, PASSWD) VALUES ("Alam", "Brito", "alambrito@gmail.com", "123");
INSERT INTO USUARIOS (NOMBRE, APELLIDO, EMAIL, PASSWD) VALUES ("Jhon", "Doe", "jhondoe@gmail.com", "123");
SELECT ID, NOMBRE, APELLIDO, EMAIL, CONCAT(NOMBRE, " ", APELLIDO) AS NOMBRE_COMPLETO FROM USUARIOS WHERE EMAIL = "alambrito@gmail.com" AND PASSWD = "123";

CREATE TABLE CATEGORIAS (
	ID  INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL
)  ENGINE=INNODB CHARACTER SET utf8 COLLATE utf8_general_ci;

INSERT INTO CATEGORIAS (NOMBRE) VALUES ("Producto");
INSERT INTO CATEGORIAS (NOMBRE) VALUES ("Servicio");

CREATE TABLE TIPOS_CLASIFICADO (
	ID  INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL
)  ENGINE=INNODB CHARACTER SET utf8 COLLATE utf8_general_ci;

INSERT INTO TIPOS_CLASIFICADO (NOMBRE) VALUES ("Belleza");
INSERT INTO TIPOS_CLASIFICADO (NOMBRE) VALUES ("Reparaciones");
INSERT INTO TIPOS_CLASIFICADO (NOMBRE) VALUES ("Comidas");

CREATE TABLE MUNICIPIOS (
	ID  INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL
)  ENGINE=INNODB CHARACTER SET utf8 COLLATE utf8_general_ci;

-- SELECT * FROM MUNICIPIOS;
INSERT INTO MUNICIPIOS (NOMBRE) VALUES ("Medellín");
INSERT INTO MUNICIPIOS (NOMBRE) VALUES ("Bello");
INSERT INTO MUNICIPIOS (NOMBRE) VALUES ("Copacabana");
INSERT INTO MUNICIPIOS (NOMBRE) VALUES ("Envigado");
INSERT INTO MUNICIPIOS (NOMBRE) VALUES ("Itaguí");
INSERT INTO MUNICIPIOS (NOMBRE) VALUES ("Sabaneta");
INSERT INTO MUNICIPIOS (NOMBRE) VALUES ("La Estrella");
INSERT INTO MUNICIPIOS (NOMBRE) VALUES ("Caldas");

CREATE TABLE CLASIFICADOS (
	ID  INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    DESCRIPCION VARCHAR(300) NOT NULL,
    FOTO VARCHAR(250) NOT NULL,
    FACEBOOK VARCHAR(100) NULL,
    INSTAGRAM VARCHAR(100) NULL,
    TWITTER VARCHAR(100) NULL,
    DIRECCION VARCHAR(250) NULL,
    CELULAR VARCHAR(15) NOT NULL,
    CATEGORIA INT NOT NULL,
    TIPO_CLASIFICADO INT NOT NULL,
    MUNICIPIO INT NOT NULL,
    USUARIO INT NOT NULL,
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (CATEGORIA) REFERENCES CATEGORIAS(ID),
    FOREIGN KEY (TIPO_CLASIFICADO) REFERENCES TIPOS_CLASIFICADO(ID),
    FOREIGN KEY (MUNICIPIO) REFERENCES MUNICIPIOS(ID),
    FOREIGN KEY (USUARIO) REFERENCES USUARIOS(ID)
)  ENGINE=INNODB CHARACTER SET utf8 COLLATE utf8_general_ci;

INSERT INTO CLASIFICADOS (NOMBRE, DESCRIPCION, FOTO, CELULAR, CATEGORIA, TIPO_CLASIFICADO, MUNICIPIO, USUARIO) VALUES ('Peluquería', 'Servicios de belleza', 'image', '3214444444', 2, 1 , 1, 1);
INSERT INTO CLASIFICADOS (NOMBRE, DESCRIPCION, FOTO, CELULAR, CATEGORIA, TIPO_CLASIFICADO, MUNICIPIO, USUARIO) VALUES ('Hamburquesas JD', 'Hamburguesas a domicilio', 'image', '3214555444', 1, 3 , 5, 2);
INSERT INTO CLASIFICADOS (NOMBRE, DESCRIPCION, FOTO, CELULAR, CATEGORIA, TIPO_CLASIFICADO, MUNICIPIO, USUARIO) VALUES ('Taller', 'Servicio técnico automotor', 'image', '3216664444', 2, 2 , 4, 1);


SELECT ID, NOMBRE, DESCRIPCION, FOTO, FACEBOOK, INSTAGRAM, TWITTER, DIRECCION, CELULAR, CATEGORIA, TIPO_CLASIFICADO, MUNICIPIO, USUARIO, FECHA_CREACION FROM clasificados;

SELECT ID, NOMBRE, DESCRIPCION, FOTO, FACEBOOK, INSTAGRAM, TWITTER, DIRECCION, CELULAR, CATEGORIA, TIPO_CLASIFICADO, MUNICIPIO, USUARIO, FECHA_CREACION FROM clasificados ORDER BY FECHA_CREACION DESC LIMIT 2;

