CREATE DATABASE CLASIFICADOSAPP;
USE CLASIFICADOSAPP;

CREATE TABLE USUARIOS (
	ID  INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL,
    APELLIDO VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    PASSWD VARCHAR(8) NOT NULL
)  ENGINE=INNODB CHARACTER SET utf8 COLLATE utf8_general_ci;

INSERT INTO USUARIOS (NOMBRE, APELLIDO, EMAIL, PASSWD) VALUES ("Alam", "Brito", "alambrito@gmail.com", "123");
SELECT ID, NOMBRE, APELLIDO, EMAIL, CONCAT(NOMBRE, " ", APELLIDO) AS NOMBRE_COMPLETO FROM USUARIOS WHERE EMAIL = "alambrito@gmail.com" AND PASSWD = "123";

CREATE TABLE CATEGORIAS (
	ID  INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL
)  ENGINE=INNODB CHARACTER SET utf8 COLLATE utf8_general_ci;

INSERT INTO CATEGORIAS (NOMBRE) VALUES ("Producto");
INSERT INTO CATEGORIAS (NOMBRE) VALUES ("Servicio");

CREATE TABLE TIPOS_CLASIFICADO (
	ID  INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL
)  ENGINE=INNODB CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE TABLE ZONAS (
	ID  INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL
)  ENGINE=INNODB CHARACTER SET utf8 COLLATE utf8_general_ci;

INSERT INTO ZONAS (NOMBRE) VALUES ("Zona 1 - Nororiental");
INSERT INTO ZONAS (NOMBRE) VALUES ("Zona 2 - Noroccidental");
INSERT INTO ZONAS (NOMBRE) VALUES ("Zona 3 - Centro oriental");
INSERT INTO ZONAS (NOMBRE) VALUES ("Zona 4 - Centro occidental");
INSERT INTO ZONAS (NOMBRE) VALUES ("Zona 5 - Suroriental");
INSERT INTO ZONAS (NOMBRE) VALUES ("Zona 6 - Suroccidental");

CREATE TABLE COMUNAS (
	ID  INT AUTO_INCREMENT PRIMARY KEY,
    ZONA INT NOT NULL,
    NOMBRE VARCHAR(50) NOT NULL,
    FOREIGN KEY (ZONA) REFERENCES ZONAS(ID)
)  ENGINE=INNODB CHARACTER SET utf8 COLLATE utf8_general_ci;

SELECT * FROM COMUNAS;
INSERT INTO COMUNAS (ZONA, NOMBRE) VALUES (1, "Comuna 1 - Popular");
INSERT INTO COMUNAS (ZONA, NOMBRE) VALUES (1, "Comuna 2 - Santa Cruz");
INSERT INTO COMUNAS (ZONA, NOMBRE) VALUES (1, "Comuna 3 - Manrique");
INSERT INTO COMUNAS (ZONA, NOMBRE) VALUES (1, "Comuna 4 - Aranjuez");
INSERT INTO COMUNAS (ZONA, NOMBRE) VALUES (2, "Comuna 5 - Castilla");
INSERT INTO COMUNAS (ZONA, NOMBRE) VALUES (2, "Comuna 6 - Doce de octubre");
INSERT INTO COMUNAS (ZONA, NOMBRE) VALUES (2, "Comuna 7 - Robledo");
INSERT INTO COMUNAS (ZONA, NOMBRE) VALUES (3, "Comuna 8 - Villa Hermosa");
INSERT INTO COMUNAS (ZONA, NOMBRE) VALUES (3, "Comuna 9 - Buenos Aires");
INSERT INTO COMUNAS (ZONA, NOMBRE) VALUES (3, "Comuna 10 - La Candelaria");
INSERT INTO COMUNAS (ZONA, NOMBRE) VALUES (4, "Comuna 11 - Laureles—Estadio");
INSERT INTO COMUNAS (ZONA, NOMBRE) VALUES (4, "Comuna 12 - La América");
INSERT INTO COMUNAS (ZONA, NOMBRE) VALUES (4, "Comuna 13 - San Javier");
INSERT INTO COMUNAS (ZONA, NOMBRE) VALUES (5, "Comuna 14 - Poblado");
INSERT INTO COMUNAS (ZONA, NOMBRE) VALUES (6, "Comuna 15 - Guayabal");
INSERT INTO COMUNAS (ZONA, NOMBRE) VALUES (6, "Comuna 16 - Belén");

CREATE TABLE CLASIFICADOS (
	ID  INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    DESCRIPCION VARCHAR(300) NOT NULL,
    FOTO VARCHAR(250) NOT NULL,
    FACEBOOK VARCHAR(100) NOT NULL,
    INSTAGRAM VARCHAR(100) NOT NULL,
    TWITTER VARCHAR(100) NOT NULL,
    DIRECCION VARCHAR(250) NOT NULL,
    CELULAR INT(10) NOT NULL,
    CATEGORIA INT NOT NULL,
    TIPO_CLASIFICADO INT NOT NULL,
    COMUNA INT NOT NULL,
    USUARIO INT NOT NULL,
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (CATEGORIA) REFERENCES CATEGORIAS(ID),
    FOREIGN KEY (TIPO_CLASIFICADO) REFERENCES TIPOS_CLASIFICADO(ID),
    FOREIGN KEY (COMUNA) REFERENCES COMUNAS(ID),
    FOREIGN KEY (USUARIO) REFERENCES USUARIOS(ID)
)  ENGINE=INNODB CHARACTER SET utf8 COLLATE utf8_general_ci;
